version: 2
jobs:
  build:
    docker:
      - image: circleci/node:6.10.3
    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: npm lint
      - run: npm test
      - run: npm build
      - run: git checkout --orphan gh-pages
      - run: git rm -rf .
      - run: rm '.gitignore'
      - run: mv dist/ .
      - run: git commit -a -m "Github pages"
      - run: git push origin gh-pages --force
